---
- 
  name: Download openVPN on ubuntu server
  hosts: vpn
  become: true

  # apt update and apt install openvpn easy-rsa net-tools
  roles:
    - install_packages
    - openVPN_Basic_Server_Setup
    - openVPN_CreateCert
