---
# tasks file for openVPN_Basic_Server_Setup

- name: Enable IP forwarding via sysctl
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Add NAT masquerade rule to iptables
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    protocol: all
    source: '10.8.0.0/24'
    destination: '0.0.0.0/0'
    jump: MASQUERADE
    comment: Ansible NAT MASQUERADE
  notify: save iptables rules

